#!/usr/bin/env python3
"""EDU FORGE profundidad — contenido docente denso por semana.

Cada entrada añade a la semana: objetivo de aprendizaje, lectura principal
sustancial y práctica guiada verificable. El generador la fusiona en
semana-NN.md y en la página del curso. Patrón escalable: para profundizar
más semanas solo se añaden entradas aquí (semana: {objetivo, lectura, practica}).
"""

PROFUNDIDAD: dict[str, dict[int, dict]] = {}

PROFUNDIDAD["ciber-ofensiva"] = {
    5: {
        "objetivo": "Convertir información pública dispersa en un mapa accionable del objetivo sin enviar un solo paquete a su infraestructura.",
        "lectura": "El reconocimiento avanzado empieza por el dominio: certificados (crt.sh revela subdominios históricos), registros DNS (MX, TXT, NS delatan proveedores y a veces relaciones corporativas), Wayback Machine (versiones borradas de portales con datos útiles) y metadatos de documentos públicos (autor, plantilla, rutas internas). Las Google dorks sistematizan la búsqueda: site:, filetype:pdf, inurl:admin, cache:. El perfilado de personas con responsabilidad (LinkedIn, publicaciones, charlas) alimenta la ingeniería social ética: no para engañar, sino para saber qué phishing simularíamos en el informe. La regla profesional: todo lo que OSINT encuentra se documenta con fecha y fuente, porque el informe ético cita evidencia verificable, nunca capturas sin contexto. Un recon pasivo bien hecho responde tres preguntas antes de tocar nada: qué superficie existe, quién la administra y qué valor tiene para el alcance firmado.",
        "practica": "Elige un dominio que te pertenezca o uno con programa bug bounty público. Extrae: 10+ subdominios (crt.sh), 3 tecnologías visibles, 2 correos corporativos públicos y 1 documento con metadatos. Redacta el perfil en una página con fuente y fecha por dato.",
    },
    6: {
        "objetivo": "Modelar al adversario con árboles de ataque y decidir qué rutas proteger primero con el presupuesto disponible.",
        "lectura": "Un árbol de ataque (Schneier) pone el objetivo del atacante en la raíz —por ejemplo 'exfiltrar la base de clientes'— y descompone los caminos en ramas con condiciones AND/OR: obtener credenciales de VPN O explotar el portal expuesto Y esquivar el WAF. Cada hoja recibe coste para el atacante y probabilidad estimada; el defensista poda primero las ramas de menor coste y mayor probabilidad. MITRE ATT&CK complementa el modelo con tácticas y técnicas reales observadas (reconocimiento, acceso inicial, persistencia, movimiento lateral, exfiltración), dando vocabulario común al rojo y al azul. La diferencia entre una lista de vulnerabilidades y un modelo de amenaza es que el segundo responde '¿y esto qué le permite al atacante?' — la pregunta que un comité directivo financia.",
        "practica": "Construye el árbol de 'acceso no autorizado al panel de administración' de una web ficticia con al menos 8 hojas. Marca las 2 ramas más baratas para el atacante y propón un control por rama. Contrasta tus técnicas con 3 entradas reales de ATT&CK (cita los identificadores).",
    },
    7: {
        "objetivo": "Distinguir un escáner que acumula ruido de un escaneo que produce hallazgos validados y priorizados.",
        "lectura": "Los escáneres (OpenVAS, Nessus Essentials) venden cobertura; la profesionalidad está en la validación: un CVE sin Proof-of-Concept reproducible en TU contexto es una hipótesis, no un hallazgo. El flujo maduro: escaneo autenticado (ve más que el anónimo), deduplicación (el mismo servicio reportado por 4 vías es un activo), verificación manual del top-10 por severidad, y priorización por explotabilidad real — EPSS estima probabilidad de explotación en producción y CVSS mide impacto teórico; juntos valen más que cualquiera solo. Se descarta lo inalcanzable por red y se re-testea tras parchear: el escaneo de verificación cierra el ciclo. Documentar falso positivo es obligatorio: enseñar por qué algo parecía grave y no lo es educa al cliente y afina el próximo escaneo.",
        "practica": "Escanea tu VM de laboratorio con OpenVAS. Toma los 3 hallazgos de mayor severidad y valida cada uno: ¿reproducible? ¿alcanzable desde tu posición? ¿tiene PoC público? Asigna prioridad final combinando CVSS + reachability y explica una exclusión (falso positivo o no explotable) razonada.",
    },
    8: {
        "objetivo": "Ejecutar los riesgos web del OWASP Top 10 en laboratorio legal y documentarlos en formato de informe profesional.",
        "lectura": "El Top 10 se domina tocándolo: inyección SQL (entrada que se convierte en consulta — prueba con delimitadores y observa errores, luego UNION y ciegas con retardos), control de acceso roto (cambiar id=17 por id=18 en un perfil ajeno: el servidor confió en el cliente), XSS reflejado y almacenado (tu script viaja al navegador de otra persona), SSRF (el servidor pide la URL que tú le das: alcanza su red interna), y componentes obsoletos (la biblioteca de 2016 con CVE conocido que nadie actualizó). En Juice Shop cada reto mapea una categoría con pista y solución oficial: úsalo como gimnasio, pero el entregable profesional es el informe: título, severidad CVSS con vector, reproducción paso a paso, captura con contexto y remediación concreta (no 'actualizar', sino 'pasar a versión X y aplicar prepared statements en login').",
        "practica": "En Juice Shop local: resuelve un reto de inyección, uno de control de acceso y uno de XSS. Escribe los 3 hallazgos en formato de informe (CVSS + vector, pasos, evidencia, remediación). Un compañero debe poder reproducirlos siguiendo tus pasos sin preguntarte nada.",
    },
}

PROFUNDIDAD["ciber-defensiva"] = {
    5: {
        "objetivo": "Operar el triaje de un SOC: convertir una avalancha de alertas en una cola priorizada de incidentes reales.",
        "lectura": "El analista N1 vive del triaje: cada alerta se clasifica en segundos con un método fijo — ¿es de un activo que importa? ¿el comportamiento encaja en la línea base? ¿hay correlato en otros sistemas? ¿la severidad del artefacto coincide con el contexto? Las colas maduras separan verdaderos positivos, falsos positivos documentados (que alimentan el tuning) y ruido recurrente (candidato a supresión con justificación). La métrica sana no es 'alertas cerradas' sino tiempo medio de triaje y tasa de escalado con sentido: escalar todo es no escalar nada. El runbook por tipo de alerta (login fallido masivo, imposible travel, EICAR, creación de admin) convierte la intuición del veterano en procedimiento auditable que el nuevo puede ejecutar el primer día.",
        "practica": "Simula 10 alertas mezclando verdaderos y falsos positivos (usa las generadas en el lab de Wazuh). Triaje cada una en la plantilla: activo/criticidad, línea base, decisión (cerrar/escalar/suprimir) y justificación de una línea. Calcula tu tiempo medio por alerta.",
    },
    6: {
        "objetivo": "Escribir detecciones traducibles a cualquier SIEM usando Sigma y pensar como ingeniero de detección, no como consumidor de reglas.",
        "lectura": "Sigma es a la detección lo que SQL a las bases: un YAML declarativo que describe un patrón de log (evento, campos, condición) y se convierte automáticamente a la sintaxis de Splunk, Sentinel, Elastic o Wazuh. Escribir una regla propia obliga a conocer el log: selección (Image endsWith 'whoami.exe' y ParentImage contiene 'winword.exe' huele a macro ofimática ejecutando reconocimiento), filtros que restan falsos positivos legítimos, y nivel/Descripción que expliquen el porqué a quien la herede. La disciplina de detección incluye versionar reglas en git, probarlas contra logs de ataque conocidos (Atomic Red Team genera los eventos) y medir su ruido en 7 días antes de promoverlas a producción.",
        "practica": "Escribe una regla Sigma para 'creación de usuario y añadido a administradores en menos de 5 minutos'. Conviértela con sigma-cli a la sintaxis del SIEM de tu lab (o valida el YAML con el convertidor público). Genera el evento en tu VM y demuestra que dispara; genera también el uso legítimo y documenta cómo lo filtrarías.",
    },
    7: {
        "objetivo": "Dirigir la respuesta a un incidente real siguiendo NIST 800-61r3 sin destruir evidencia por el camino.",
        "lectura": "El ciclo moderno (Preparación → Detección y análisis → Contención, erradicación y recuperación → Actividad post-incidente) cambia el énfasis: la contención se decide con una matriz de opciones (aislar host, bloquear cuenta, cortar C2) valoradas por impacto en negocio y velocidad, porque apagar todo es contenerse uno mismo. La evidencia se preserva ANTES de limpiar: memoria y disco del host comprometido, logs del salto previo y posterior, y cadena de custodia con hashes — el forense que llega tarde solo encuentra el incendio extinguido y las huellas barridas. La comunicación es parte del incidente: quién informa a quién, cada cuánto, y qué NO se escribe en canales no privilegiados. El post-incidente no es optional: lecciones, plazos y dueños; sin él el mismo atacante vuelve por el mismo agujero.",
        "practica": "Juego de rol cronometrado: ransomware detectado en 3 equipos. Escribe tus primeras 6 decisiones en orden con timestamp, la lista de evidencia a preservar antes de limpiar, y el borrador de post-incidente (causa raíz hipótesis, 3 acciones con dueño y fecha). Contrasta con el caso real de tu elección (hay transparencias públicas de incidentes).",
    },
    8: {
        "objetivo": "Consumir inteligencia de amenazas con escepticismo operativo: enriquecer, priorizar y cerrar el ciclo de feedback.",
        "lectura": "La inteligencia útil responde preguntas de decisión, no colecciona IOCs: estratégica (qué actores atacan mi sector y con qué motivación), táctica (qué TTPs de ATT&CK debo cubrir) y operativa (estos hashes/ IPs/dominalos son malos PARA MÍ ahora). Un TIP mínimo ingesta feeds (AlienVault OTX abierta, MISP autoalojado), deduplica, aplica expiración — un IOC de 2023 bloqueado hoy genera falsos positivos y calma falsa — y sobre todo se enriquece con lo propio: el IP que te escaneó ayer vale más que mil genéricos. Pirámide del dolor: bloquear hash es trivial para el atacante de esquivar; degradar sus TTPs es caro. El ciclo termina midiendo qué IOC disparó detección real y alimentando el tuning: inteligencia sin feedback es decoración cara.",
        "practica": "Configura una cuenta OTX y suscríbate a 2 pulses relevantes para tu sector. Exporta 20 IOC, aplícales expiración razonable y clasifícalos en la pirámide del dolor. Diseña en una página tu TIP mínimo: fuentes, deduplicación, expiración, y el informe semanal que justificaría su coste.",
    },
}

PROFUNDIDAD["ia-aplicada-segura"] = {
    5: {
        "objetivo": "Diseñar un pipeline MLOps donde la seguridad es un requisito del ciclo de vida, no un parche final.",
        "lectura": "Un pipeline de ML seguro versiona tres cosas que los pipelines ingenuos pierden: datos (con linaje: de dónde vino cada dataset y quién lo tocó — DVC lo hace accesible), código y modelo (con firma: un .pbin sin hash es un binario cualquiera que podría haber sido sustituido). Los checkpoints se validan antes de promover: tests de datos (esquema, rangos, nulos), tests de modelo (rendimiento mínimo por segmento, no solo global — un modelo que acierta 95 % fallando siempre en un colectivo no promociona) y tests de seguridad (carga solo de fuentes allowlisteadas). El despliegue registra qué modelo, con qué datos y qué configuración sirvió cada predicción: sin eso no hay auditoría posible ni rollback responsable. La regla de oro heredada de DevSecOps aplica igual: si puede reconstruirse desde el repositorio con un comando, puede auditarse; si depende de un portátil de alguien, es deuda.",
        "practica": "Esquematiza tu pipeline (papel o draw.io) para un clasificador de spam: versionado de datos, firma de artefactos, 3 gates de promoción y el registro de serving. Marca en rojo los 2 puntos donde hoy un atacante interno podría colar un modelo adulterado y propón el control.",
    },
    6: {
        "objetivo": "Someter un modelo a pruebas de robustez adversaria y cuantificar su degradación antes de que lo haga un atacante.",
        "lectura": "La robustez se testea como se testea la criptografía: asumiendo el peor caso. Para imágenes, perturbaciones imperceptibles (ataques L∞ tipo FGSM/PGD) voltean la predicción: la pegatina hace que la señal de STOP desaparezca para el modelo. Para tablas y texto, la pregunta es qué pasa con entradas fuera de distribución — el modelo contesta con confianza de siempre. El testeo práctico usa herramientas abiertas (Adversarial Robustness Toolbox de IBM, Foolbox) sobre TUS datos y mide: tasa de éxito del ataque, distancia de la perturbación y degradación de métrica global. Defender cuesta: entrenamiento adversarial y detección de out-of-distribution añaden coste y a veces accuracy — la decisión informada es cuánta robustez compra el caso de uso (un filtro de spam tolera más que un sistema de conducción). Documentar el nivel aceptado es la entrega, no 'hemos probado que es robusto'.",
        "practica": "Con ART y un modelo pequeño entrenado en clase (o un MNIST público): ejecuta FGSM y PGD, y reporta accuracy limpio vs atacado y ejemplo de perturbación mínima que engaña. Escribe el párrafo de decisión: nivel de robustez aceptado para un caso de uso real y por qué.",
    },
    7: {
        "objetivo": "Blindar el suministro de datos y modelos contra envenenamiento y sustitución, aplicando las lecciones de la supply chain clásica.",
        "lectura": "El envenenamiento corrompe el aprendizaje: datos falsos insertados en el corpus (etiquetas cambiadas, backdoors activables con un trigger) o dependencias ML adulteradas — la lección de event-stream/PyPI aplica a datasets y pesos descargados: ¿quién firmó ese .safetensors? Las defensas son aburridas y efectivas: fuentes allowlisteadas con hash fijado, análisis de datos antes de entrenar (distribución, duplicados sospechosos, outlier forense), separación de quien aporta datos de quien aprueba entrenar (four-eyes), y canaries en datasets — registros sintéticos únicos que, si aparecen en la salida de un modelo ajeno, delatan robo o memorización. Para modelos preentrenados de terceros: preferir fuentes con atestación, re-entrenar la última capa en dominio propio reduce superficie, y monitorear comportamiento en producción contra una batería dorada de casos conocidos.",
        "practica": "Diseña el manifiesto de suministro de tu proyecto ML: qué datasets/pesos/bibliotecas entran, con qué hash y de qué fuente, quién aprueba cambios. Añade 3 canaries sintéticos a tu dataset y describe la alarma que dispararían. Doc: media página.",
    },
    8: {
        "objetivo": "Proteger la propiedad intelectual del modelo frente a extracción y distilación no autorizada, midiendo el riesgo real.",
        "lectura": "Un modelo desplegado es un oráculo: consultando bastante (y con presupuesto) se puede reconstruir su comportamiento — extracción de membresía ('este dato estaba en el entrenamiento' — riesgo RGPD directo), robo de funcionalidad por distilación (un modelo estudiante imita al tuyo), o inversión de datos de entrenamiento (reconstruir ejemplos memorizados). Mitigaciones con coste: limitación de tasa y presupuestos por identidad (la nube ofrece cuotas), ruido en salidas o predicciones top-k recortadas (menos información por consulta), regularización contra memorización, y monitoreo del patrón de consultas — quien pide esquinas sistemáticas del espacio de entrada no es un usuario. La pregunta de negocio decide: ¿qué pierdo si me copian el modelo? Si la respuesta es 'nada crítico', el control correcto es mínimo; si es 'la ventaja competitiva', el blindaje justifica su coste.",
        "practica": "Para tu caso de uso: tabla de activos (pesos, datos, prompts propietarios) × riesgo (extracción/distilación/membresía) × impacto. Propón 3 controles con su coste y qué patrón de consultas usarías como alarma. Media página con decisión explícita.",
    },
}

PROFUNDIDAD["gobernanza-compliance"] = {
    5: {
        "objetivo": "Gestionar el riesgo con un proceso repetible (ISO 31000 / NIST 800-39) donde cada riesgo tiene dueño, fecha y evidencia.",
        "lectura": "ISO 31000 da el proceso (identificar → analizar → valorar → tratar → monitorear) y NIST 800-39 lo aterriza en seguridad con cuatro respuestas posibles: mitigar, compartir, aceptar o evitar. La práctica que separa el papel de la gestión: el registro de riesgos vivo — cada fila con activo, amenaza, controles actuales, probabilidad × impacto con escala definida (¿qué significa 'alto' aquí, con criterio numérico?), decisión, dueño con nombre y apellido, y fecha de revisión. Los riesgos aceptados se firman por quien asume la consecuencia, no por quien los encontró. Y el marco se calibra: riesgo residual después de controles, no riesgo bruto de catálogo. La auditoría madura pregunta por el ciclo: muéstrame un riesgo cerrado el trimestre pasado con su evidencia de tratamiento — no una matriz bonita sin historia.",
        "practica": "Construye el registro de 8 riesgos reales de la plataforma (fuga de material, token robado, caída de CDN, abuso de API…). Escala definida, valoración bruto/residual, decisión, dueño y revisión. Firma (simulada) los 2 aceptados y explica por qué esa persona.",
    },
    6: {
        "objetivo": "Calcular el impacto en el negocio y diseñar continuidad que sobreviva al peor día, no al promedio.",
        "lectura": "El BIA (Business Impact Analysis) responde dos preguntas por proceso: cuánto aguanto parado (RTO — tiempo objetivo de recuperación) y cuánto pierdo por unidad de tiempo de datos (RPO — ventana de pérdida tolerable). Con eso se ordena la inversión: el proceso con RTO de minutos exige redundancia activa; el de días, un procedimiento manual documentado. La continuidad (BCP/DRP) se escribe para escenarios concretos — ransomware total, caída del proveedor cloud principal, pérdida del personal clave — y se valida el único modo honesto: probándolo. El test de restauración trimestral del backup es el ritual más rentable de la lista: el backup no probado es una esperanza. Métrica final: el plan se mide en el incidente (¿se recuperó dentro del RTO?), no en la página del PDF.",
        "practica": "BIA de 5 procesos de la plataforma (serving del campus, generación, credenciales, búsqueda, deploy) con RTO/RPO justificados. Escenario ransomware: secuencia de recuperación paso a paso con responsables y el punto donde verificarías integridad antes de reabrir.",
    },
    7: {
        "objetivo": "Gobernar el riesgo de terceros y la cadena de suministro antes de que el proveedor sea el titular de tu incidente.",
        "lectura": "Tu superficie de ataque incluye la de tus proveedores: el CDN que te sirve, el SaaS que procesa, la biblioteca que importas. El mínimo viable de terceros: inventario con criticidad (¿qué pasa si cae?, ¿qué datos ve?), cláusulas de seguridad y notificación (tiempo máximo para avisarte de su incidente — sin cláusula, te enteras por la prensa), y plan de salida (los datos recuperables en formato abierto; el lock-in es un riesgo de continuidad). Para software: SBOM — la lista de ingredientes — y política de actualización por severidad. El test de la madurez: simula 'tu proveedor principal lleva 48h caído' y observa si alguien sabe qué hacer sin improvisar; si la respuesta es una llamada a una persona, tienes una anécdota, no un plan.",
        "practica": "Inventario de 6 terceros reales de la plataforma (GitHub, CDN, DNS, fonts…): criticidad, datos que ven, cláusula de notificación (existe/no), y plan B. Redacta la cláusula de seguridad que les exigirías (media página) y la política de SBOM mínima.",
    },
    8: {
        "objetivo": "Aplicar ingeniería de privacidad: convertir el principio de minimización en decisiones de diseño medibles (RGPD y LGPD).",
        "lectura": "La privacidad por diseño se demuestra en decisiones, no en párrafos: identificación temprana en el diseño (¿este dato es necesario para la finalidad? si no, no se recoge — el usuario-token de esta plataforma es la forma extrema), minimización en la exposición (devolver lo que la pantalla muestra, no el registro entero), limitación en la retención (TTL por tipo de dato con borrado verificable — incluidos los backups con plan), y transparencia real (qué se guarda, cuánto y cómo ejercer derechos, sin abogado intermediario). RGPD y LGPD comparten núcleo — ambos exigen base legal, finalidad declarada, seguridad proporcional y derechos efectivos — por lo que un diseño doble-obedece casi gratis. La técnica de QA: la auditoría del formulario de la semana pasada se repite como regression test de privacidad: cada campo que reaparece sin justificación rompe el build, no la promesa.",
        "practica": "Toma un flujo real con datos (registro o analytics) y aplica las 5 decisiones: campo a conservar/quitar, TTL, exposición minimizada, base legal y texto de transparencia de 3 líneas. Añade el test de regresión que falla si un campo injustificado reaparece.",
    },
}
